### ISSUE TITLE
Nonunique results or predicts no results.

### ISSUE THREAD

**Issue by pythonlover8** [crotwell/TauP#10]
Hi, Philip. 
I am trying to use TauP program to estimate the takeoff angles of the seismic rays. But it gives me more than one result. In some case, it gives me no result. Could you please explain to me why this happen? 

In this case, it gives no result and I am trying estimate the takeoff-angle of P-wave.

1994.289.05.10.04.0280.IU.YSS.00.BHZ.M.SAC
4.63018
Model: iasp91
  Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist |
     (deg)       (km)      Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
     4.63        102.1         P                                                                                       

In this case, it gives me more than one results. 
1994.289.05.12.10.0280.IU.MA2.00.BHZ.M.SAC
13.8884

Model: iasp91
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)         (km)     Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 

   13.89   102.1   P        192.31    13.001     72.99    42.70    13.89   = P    
   13.89   102.1   P        197.13    11.112     54.82    35.42    13.89   = P    
   13.89   102.1   P        197.19    11.230     55.69    35.86    13.89   = P 

Thanks!

**Comment by crotwell** [comment]
In the first case due to the small distance and depth, the p wave arrival is upgoing, so is named p instead of P.

In the second case, the 410 discontinuity is causing a triplication, so there actually really are 3 P arrivals.
