### ISSUE TITLE
Update the GMT scripts to GMT >=5  syntax

### ISSUE THREAD

**Issue by seisman** [crotwell/TauP#14]
GMT 4.5.18 was released on July 1, 2018 and is the final release of GMT 4.x series. Now there are more and more people using GMT 5.x or 6.x, but TauP tools (e.g., `taup_time` and `taup_curve` are still generating GMT 4 scripts. It would be better if TauP can produce GMT 5 scripts.

**Comment by crotwell** [comment]
Do you mean just prefixing all commands with "gmt" like "gmt psxy ..." or are they other incompatibilities you have seen?

The psxy to gmt psxy is fixed in 
https://github.com/crotwell/TauP/commit/8b530a8921250f2d0d6138d09454579e7e088ddf

and there is a prerelease with this change at
http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.5.0-SNAPSHOT.tgz

**Comment by seisman** [comment]
> Do you mean just prefixing all commands with "gmt" like "gmt psxy ..." or are they other incompatibilities you have seen?
> 
> The psxy to gmt psxy is fixed in
> [8b530a8](https://github.com/crotwell/TauP/commit/8b530a8921250f2d0d6138d09454579e7e088ddf)

Great! Now it works well for GMT 5 and GMT 6.

Some issues:

1. The last `psxy` command generated by `taup_path` can be improved. Now GMT gives a warning as the input is empty:
```
$ taup_path -ph P -deg 30 -h 30 --gmt
$ sh taup_path.gmt
psxy [WARNING]: File <stdin> is empty!
```

2. GMT 5 produces a temporary file "gmt.history" in the current directory. I think it's safe to delete the file at the end of the GMT scripts.

3. `taup_create` splot is not good:
```
$ taup_create --splot splot
```
![image](https://user-images.githubusercontent.com/3974108/104642318-c53b6380-5678-11eb-8c29-dce9ecfc409e.png)

4. GMT>=5 has different syntax for some options, but the old syntax is still valid. For example, the old GMT4 syntax is 
```
-B1a2:'Velocity (km/s)':/200a400:'Depth (km)':/:.'iasp91':WSen
```
and the new GMT>=5 syntax is more readable:
```
-Bx1a2+l'Velocity (km/s)' -By200a400+l'Depth (km)' -BWSen+t'iasp91'
```
It's OK to use the old GMT4 syntax. I'd glad to help if you want to upgrade all GMT commands to the new and more readable GMT5 syntax.

**Comment by crotwell** [comment]
>     1. The last psxy command generated by taup_path can be improved. Now GMT gives a warning as the input is empty:

Purpose of this is to end/close the postscript without having to keep track of which is the last command in the script. Happy to change it if you know of a better way, I wish gmt would have "gmt psstart" and "gmt psend" commands to do this instead of relying on the -O and -K flags. Perhaps putting in a xy value of 999999 999999 would work as it should be off the screen.

> 2. GMT 5 produces a temporary file "gmt.history" in the current directory. I think it's safe to delete the file at the end of the GMT scripts.

I am a little leery of deleting files that the user may actually want, but you are probably right about this one.

I'll will look into updating the slowness plot and the -B options in the scripts for 3. and 4.

**Comment by seisman** [comment]
> Purpose of this is to end/close the postscript without having to keep track of which is the last command in the script.  I 

https://github.com/crotwell/TauP/blob/8b530a8921250f2d0d6138d09454579e7e088ddf/src/main/java/edu/sc/seis/TauP/TauP_Path.java#L247-L251

Do lines 249-250 mean that you already know it's writing the last GMT command?

As I understand it (I know nothing about java), you can change these two lines to
```
     out.write("gmt psxy -P -R -O -JP -m -A -T >> " + psFile + "\n"); 
```
**gmt psxy -T** means ignoring input file if any. It's often used to close the GMT PS file.

> wish gmt would have "gmt psstart" and "gmt psend" commands to do this instead of relying on the -O and -K flags. 

GMT 6 provides a new *modern* mode, which simplifies GMT scripts and **-O** and **-K** flags are no longer needed. A simple **modern mode* example is (`plot` is an alias of `psxy`):
```
gmt begin example pdf
gmt plot file1.txt -R0/10/0/10 -JX10c -Baf -W1p
gmt plot file2.txt -W1p,blue
gmt end 
```
You may want to read the [GMT6](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019GC008515) paper.

Although GMT6 modern mode is much simpler, I think TauP may still want to use the _classic mode_ (the GMT5 syntax, with -K -O), as GMT5 is still widely used (BTW, GMT6 supports both *modern* and *classic* modes).



> > 1. GMT 5 produces a temporary file "gmt.history" in the current directory. I think it's safe to delete the file at the end of the GMT scripts.
> 
> I am a little leery of deleting files that the user may actually want, but you are probably right about this one.

I've never tried to read `gmt.history` even I think myself as an advanced GMT user.

**Comment by crotwell** [comment]
I think mostly fixed in https://github.com/crotwell/TauP/commit/ce79c5ca314318529f2d678175b3cf524bbac065

New snapshot at:
http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.5.0-SNAPSHOT.tgz

gmt.history is removed at end of scripts. Using -T to end plot. Fix most -B gmt option, add more labels to plots.

I think the slowness and velocity plots are ok now, I don't see the issue you showed above. Can you retest that and let me know?

**Comment by seisman** [comment]
Some tiny issues:

---

**`taup_curve --gmt`**

In the `taup_curve.gmt` script, the first command uses:
```
-Bxa20+l'Degrees' -Bya100+l'Seconds' -BWSne+t'iasp91 (h=0.0)' 
```
it would be better to change it to:
```
-Bxa20+l'Distance (degree)' -Bya100+l'Time (second)' -BWSne+t'iasp91 (h=0.0 km)'
```

---

**`taup_path -ph P -deg 60 -h 300 --gmt`**

The `taup_path.gmt` script uses `-B30p/500N`. It doesn't look like correct GMT syntax to me, although it works as expected. I would suggest using `-Bx30`, which produces the same plot.

---

**`taup_wavefront -ph P -deg 60 -h 300 --gmt`**

Same as `taup_path`, `-B30p/500N` should be `-Bx30`.

The `taup_wavefront` script misses the close command (`gmt psxy -T`) and the cleanup command (delete gmt.history) in the end.

---

**`taup_create --vplot vplot`**

The above command produces `vplot`, without the ".gmt" extension.

**`taup_create --splot splot`**

Same as above, no `.gmt` extension.

The first command `/bin/rm -f splot.psgmt.history` misses a whitespace between ps file name and gmt.history.

**Comment by crotwell** [comment]
I believe I have fixed the first 3 items.

--vplot and --splot were always kludgey, the second part of the arg was the actual output filename. So if you wanted `vplot.gmt` it would be `taup_create --vplot vplot.gmt`.  But that didn't match the way the other tools worked, so I have removed them from taup_create and added 2 new commands, run with the new single executable, so like:

`taup` velplot --nd iasp91`

or

`taup slowplot --nd prem`

Output files are taup_slownessmodel.gmt and taup_velocitymodel.gmt. I may make more changes before release, not sure I like the names. Also possibly updating these to take a --gmt flag and/or a --svg to generate svg output at some point.

New snapshot is on the www at
[http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.5.0-SNAPSHOT.tgz](http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.5.0-SNAPSHOT.tgz)

**Comment by seisman** [comment]
Just tried the new snapshot:

The script generated by `taup slowplot` still has this wrong command `/bin/rm -f taup_slownessmodel.psgmt.history` (a missing white space between PS file and gmt.history).

Others look good to me.

**Comment by seisman** [comment]
One unrelated question.

Running `taup` gives me the following message:
```
Usage: taup <tool> <options>
 where tool is one of [create, curve, path, phase, pierce, setsac, slowplot, table, time, velplot, wavefront]
 taup <tool> --help
 for help with a particular tool.
```
but in previous TauP versions, it opens a GUI window.

**Comment by crotwell** [comment]
Yes, I am still trying to figure out what to do about the gui. It is really really old code and probably needs a makeover. I guess still useful but klunky and ugly. Probably will either let `taup` with no args open the gui like before or perhaps add a `taup gui` to the tool runner, or maybe both.

**Comment by crotwell** [comment]
ver 2.5.0 released
