### ISSUE TITLE
Question: can derivatives and take-off angles be computed?

### ISSUE THREAD

**Issue by luca-s** [crotwell/TauP#25]
Dear developers, I am not an advanced user of the tool, so please forgive me if my question is naive.  I used `TauP Toolkit` to generate travel time tables and it worked very well. Thank you!

Since I would like to use `TauP Toolkit` for a locator, I would like to have some additional information other than the travel times, that is the take-off angles and the partial derivatives.  Is there a way to generate this information with `TauP Toolkit`?

**Comment by crotwell** [comment]
Do you mean using the `--generic` option to taup table? 

Which partials are you wanting? The only things currently calculated internally are displayed by `taup time`. I could add those to the `--generic`` output relatively easily, but not sure if that is what you are asking for.
 
```
taup time -h 60 -deg 30 -ph P,S  

Model: iasp91
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
   30.00    60.0   P        362.85     8.835     40.18    27.44    30.00   = P    
   30.00    60.0   S        657.32    15.653     39.53    28.23    30.00   = S    
```

**Comment by luca-s** [comment]
Me again :) I wanted to add a correction to my previous post. It doesn't make sense for `tuap table` to return the partial derivatives, those have to be computed by the locator. This is because the values have to be interpolated to reach the resolution required by the locator, so it makes sense to simply return takeoff angles and velocity/slowness. 

So all my long discussion boils down to add the takeoff angle and velocity or slowness to the output of `tuap table --generic` as you correctly proposed in the first place :)

Thank you for your patience for reading my posts.

**Comment by crotwell** [comment]
OK, so add takeoff and incident angles, might as well do both. That seems reasonable. Ray parameter is already there, 6th column.

So output would change from:
```
iasp91    14.00    600.0 P    179.80     9.658      14.00  P
```
to
```
iasp91    14.00    600.0 P    179.80     9.658      73.47    30.25    14.00  P
```

Only concern I have is changing the output format might conflict with existing users. Might add a flag to enable or a "generic with takeoff and incident angles" type, like `--generic_full` or something.

**Comment by luca-s** [comment]
> OK, so add takeoff and incident angles, might as well do both. That seems reasonable. Ray parameter is already there, 6th column.

This solution would be perfect and I am grateful for your help.

Just to be sure I correctly understand the ray parameter, can I compute the ray velocity with the following equation? 

```
Velocity [km/sec] = sin(takeoff) / rayParam * ((earthRadius - sourceDepth) * PI / 180)
```

> Only concern I have is changing the output format might conflict with existing users. Might add a flag to enable or a "generic with takeoff and incident angles" type, like --generic_full or something.

Good point. If I am not wrong the current `taup table` accepts `-generic`, `-locsat` but it also works without parameters. Maybe you could change the default behaviour, when no option is given? I'll let you decide what is best.

And what about adding also a header before the table, so that a software can parse it and detect the right columns even if a future version of `TauP` adds additional columns?

Again, thank you very much.

**Comment by crotwell** [comment]
I am not quite sure what you mean by ray velocity? You mean the wave speed as the ray leaves the source? The velocity is of course not constant along the ray. If you just want that velocity, you can get it from the velocity model at the source depth. Maybe I am misunderstanding what you want.

Header line is a good idea as well.

**Comment by luca-s** [comment]
> you mean the wave speed as the ray leaves the source? 

Exactly! I should have been clearer. 

>  If you just want that velocity, you can get it from the velocity model at the source depth.

I agree, but it would be nice to be able to retrieve all the information from a single source, that is the `TauP` output. I would like to avoid to fetch some information from `TauP` output and some from the input velocity model.

So, since the relationship from ray parameter and velocity is:

```
velocity [rad/sec] = sin(takeoff)/rayParam 
```

However if I want the velocity in [km/sec] I should compute it as:

```
velocity [km/sec]     = sin(takeoff)/rayParam * ((earthRadius - sourceDepth) * PI / 180)
```

I made few tests and It looks like I can retrieve the original velocity in the model in this way. Of course it would be nicer to have also a column with this value :)

**Comment by crotwell** [comment]
A prerelease with takeoff and incident angles in the output is here if you would like to test:
http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.7.0-SNAPSHOT.tgz

I have not added header, but did add a --csv and --json to taup table to output in CSV and JSON formats that may be useful and easier to parse and I think takes care of that need.

**Comment by luca-s** [comment]
That's fantastic. I tried it and I like both -csv and -json options. Json format is probably the preferred one for modern code, but harder to parse, while csv is perfect for a handcrafted parser, useful when a project doesn't want to add an additional dependency on a json parsing library (my project  for example). 

Thank you very much for this useful addition, I have now all the information I needed for the locator and I believe more code will rely on this output. 

I will close this issue since there is nothing more to say
