### ISSUE TITLE
Zoom feature in TauP window for Travel Path?

### ISSUE THREAD

**Issue by AnirudhKalyankar** [crotwell/TauP#26]
Hello, so I'm using Taup in WSL both in command line and TauP GUI window, but in GUI window the travel paths look very much minimised so is there any way to zoom in/out for clear visibility of paths. I have tried using cursor, keyboard shortcuts like Ctrl+Shift++ but it isn't working. Thanks

**Comment by crotwell** [comment]
I have not implemented any zooming. The only way to do it now would be to output gmt or svg from the command line and then edit after the fact. The specifying a max distance and/or max depth to focus in on the useful area would be a useful feature, but have not had time to look into it. I will keep it on the todo list.

**Comment by AnirudhKalyankar** [comment]
Ohh okay, I will try that workaround. Thank you.
