### ISSUE TITLE
Question: is it possible to take into consideration a station elevation?

### ISSUE THREAD

**Issue by luca-s** [crotwell/TauP#27]
Dear @crotwell ,

after you helped me with the issue #25 I was able to make use of the TauP output as the travel time tables for my locator. The locator uses the tables to compute the travel times of an event pick from the pick station to the event location: that is it fetches the TauP output values at `station-to-event-location distance` and `event-location depth` (it actually interpolates multiple values to reach the desired resolution).

That is working fine at regional scale, but on a small scale the station elevations might become a relevant component of the travel time and that is not considered at the moment in my locator.

A workaround I thought of would be to generate multiple travel time tables, one for each station. Each travel time table would be created altering the velocity model by adjusting the depth of the first layer accordingly to the station elevation. I believe this would work but It would also mean to generate a travel time table for each station, which is quite annoying.

So I was wondering if there is an equation that I can use to approximate the TauP output values to adjust for a station elevation. I am asking this because it might be obvious for you and you might have already done it.

thanks
Luca

**Comment by crotwell** [comment]
There is no easy way to do this as the extra elevation would change the ray that arrives at the station. You might be able to approximate it using the "surface" arriving ray paramater and the extra elevation. Probably that would be close, but could be wrong if the ray parameter changes significantly in the new model. All depends on your desired accuracy, but I would be careful with this type of "correction".

I have added a --elevation to `taup velmerge` to automatically add a crustal layer of the given thickness to the velocity model. This makes it a little easier to create a new velocity model for a station at elevation. Will be in next version.

**Comment by luca-s** [comment]
Thank you very much for your help. The new `--elevation ` option will definitely be very useful.

**Comment by crotwell** [comment]
Currently is does not. The implementation just adds an additional layer with the same velocity of the given (elevation) thickness.

A negative elevation would need to reduce the thickness of the existing top layer, which would be different. I can see about adding that.

**Comment by luca-s** [comment]
Thank you @bvanderbeek , very useful

**Comment by atrabattoni** [comment]
Is there a way to use --stadepth with taup_table ? I'm facing the same situation. I was thinking about computing distance/depth travel-time lookup tables for several station elevations.

**Comment by crotwell** [comment]
Not in the current version, but I probably can add it in a future version.

Can you file a separate issue for that?
