### ISSUE TITLE
Problem with underside reflections

### ISSUE THREAD

**Issue by bvanderbeek** [crotwell/TauP#29]
I cannot seem to get the syntax correct for an underside reflection. From the manual, if I wanted to predict the travel-time of a P-wave reflected off an internal crustal interface at 20 km depth (i.e. similar path as a pP but the reflection point is an interface in the crust rather than the free surface), the phase should be named 'p^20P' and the TauP call would be,

```
taup_time -mod ak135 -deg 60 -h 100 -ph p^20P
```

But TauP returns the error,

```
Error starting tool: time java.lang.NumberFormatException: empty String
```

Am I doing something wrong in defining the phase name or is there a problem with the TauP phase parsing? Interestingly, P^20P phase gives a valid result.

Thanks for the help!

**Comment by bvanderbeek** [comment]
Great! Pre-release is working for me. This relates to another issue I saw posted but my interest in modelling such phases was a kludge attempt at adding elevation by extending a reference velocity model by 9 km (i.e. just beyond highest point on Earth) and adding an interface at that same depth to mark 'true' radius. Now all station are 'inside' the Earth and elevation can be accounted for with the --stadepth flag.

I tested this for direct phases and it appears to work:

```
# Original AK135
taup_time -mod ak135.tvel -ph P -deg 60 -h 100 --stadepth 0

Model: ak135.tvel
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
   60.00   100.0   P        595.99     6.836     30.18    20.89    60.00   = P 

# Extended AK135 (depths shifted by 9 km)
taup_time -mod ak135_ext9km.tvel -ph P -deg 60 -h 109 --stadepth 9

Model: ak135_ext9km  Receiver Depth: 9.0 km
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
   60.00   109.0   P        595.99     6.836     30.18    20.89    60.00   = P

```

But I can't reproduce travel-times for surface reflected phase:

```
# Original AK135
taup_time -mod ak135.tvel -ph pP -deg 60 -h 100 --stadepth 0

Model: ak135.tvel
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
   60.00   100.0   pP       620.63     6.904    149.50    21.11    60.00   = pP

# Extended AK135 (depths shifted by 9 km)
taup_time -mod ak135_ext9km.tvel -ph p^9P -deg 60 -h 109 --stadepth 9

Model: ak135_ext9km  Receiver Depth: 9.0 km
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
   60.00   109.0   p^9P     623.52     6.908    149.47    21.12    60.00   = p^9P
```

**Comment by bvanderbeek** [comment]
In any case, you addressed the main issue I raised so I'll close this issue. Thanks again.

**Comment by crotwell** [comment]
If you extend the crust by 9km but it is the same velocity as the crust, then there is no discontinuity to reflect off of at the old surface (9km depth). The phase parser looks for the closest discontinuity to the depth given, so you are actually getting a surface reflection.

There is a bug with the "purist phase name" in this case that I will fix, it should be `pP`.

You can try adding a very small, like 0.01km/s discontinuity if you want to see the underside reflection from the 9km layer.

**Comment by bvanderbeek** [comment]
Yes, this is exactly what I did (and subsequently modified my comment). Now I can reproduce pP times with the extended model. Thanks again for the input!
