### ISSUE TITLE
Need help with creating custom velocity model in TauP

### ISSUE THREAD

**Issue by AnirudhKalyankar** [crotwell/TauP#30]
Hello all,

I wanted to create a velocity model based on the CRUST1.0 dataset for my analysis work, is there any tutorial or if anyone can give me some leads on how to start with that I would really be thankful. Currently I have downloaded the CRUST1.0 data as fortran files and also matlab file.

**Comment by crotwell** [comment]
You just need to edit the crust section within an existing model file. Have
you read the TauP documentation? There is a chapter on how to modify
velocity models.
http://www.seis.sc.edu/downloads/TauP/taup.pdf

I can answer specific questions if you have problems with TauP itself, but
crust1 is not my code and so can't provide support for it.

Good luck,
Philip

**Comment by AnirudhKalyankar** [comment]
Hey thanks for the response, I'm really sorry I couldn't reply back due to some personal reasons. Yeah I have read the documentation but my doubt was does TauP have option to set the velocity data to all the latitude and longitude pairs of Earth under one velocity model?

Explanation:
-> The CRUST1.0 velocity file which I have is 1°x1° resolution dataset that means for whole earth (lets say) I will have total 360*180 .nd (named discontinuity) files.
-> Can I anyway integrate all this under one velocity model so that I can get accurate ray path traverse info, because if I go with the docs I will make 1 nd file with some velocity and depth data then that will be treated as constant irrespective of location on earth (example same moho depth everywhere which may not be true as I'm working on continental collision region)

Thank you.

**Comment by crotwell** [comment]
There is no way in TauP to have a velocity model that is limited to a specific lat/lon range. TauP is a 1D model, so it assumes that the whole earth is the same model. So you would have to make a separate .nd file for each 1x1 degree area and you would have to be responsible for using the correct model for the event/station location and would also have to decide on which to use when the event and the station are in separate grid cells. There is no way currently to take a ray from one model that switch to another model midway, even if the model only differs at shallower layers. I have thought about that as a "1.5D" model but there are lots of small complications.

I have thought about an option to automatically merge a crust1.0 crust model onto a global earth model, but have not implemented it yet. I will consider it as Crust1.0 based models are probably a common need, so may be worth looking at more, but the bookkeeping is tricky and I don't want to implement something that generates unexpected results and causes more confusion.

**Comment by AnirudhKalyankar** [comment]
Ohh, yeah I understood the complexity. Thank you for the support.
