### ISSUE TITLE
Models without core and without liquid core

### ISSUE THREAD

**Issue by lynlyf** [crotwell/TauP#35]
Hello,

Can Taup calculate travel time and ray parameter tables and wavefronts for models having no core? For example, the simplest case, a homogeneous sphere.

And how to calculate time table for phases with S legs in models with a solid core, since there is no such naming convention in the FDSN standard?

Thanks.

**Comment by crotwell** [comment]
Yes, it should work but may require using the "nd" format as tvel doesn't let you specify layer boundaries. Just let bottom of mantle be same as radius of planet for no core and leave out liquid outer core if not needed.

For example:
```
     0.000      6.2000      3.7000      3.3198
    35.000      6.2000      3.7000      3.3198
mantle
    35.000      8.2000      4.7000      3.3198
  2889.000   13.6908    7.3015    5.5515
outer-core
inner-core
  2889.000   11.0914    3.4385   12.7037
  6371.000   11.2409    3.5645   13.0122
```

Phase naming is still the same, but with a solid core you would use `S` for mantle only S waves and `SJS` for S waves crossing into the (inner) core.

For example:
```
taup time --mod noOuterCore.nd -ph S,SJS -deg 35

Model: noOuterCore
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
   35.00     0.0   S        781.38    19.120     39.51    39.51    35.00   = S    
```

```
taup time --mod noOuterCore.nd -ph S,SJS -deg 170

Model: noOuterCore
Distance   Depth   Phase   Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name    Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------
  170.00     0.0   SJS     3076.87     7.983     15.40    15.40   190.00   = SJS  
```

**Comment by crotwell** [comment]
closing this, but let me know if you have trouble with a particular model
