### ISSUE TITLE
^ and v notations for the inner core discontinuities

### ISSUE THREAD

**Issue by 79seismo** [crotwell/TauP#4]
Hi Philip,
The Taup manual that I have says that ^ and v notations are not implemented for the inner core. I, however, believe that time has come to implement these for the inner core. There are a few inner core models, in which internal discontinuities are predicted. Thus, it would be nice to verify multipathing effects due to these discontinuities with taup toolkit.

Thanks !

Januka

**Comment by crotwell** [comment]
Can you give a link to models with the discontinuities in the inner core? Would be useful as I think about how to implement this.

**Comment by crotwell** [comment]
Will need a naming convention because p is to P is not the same as i is to I.

**Comment by 79seismo** [comment]
Here are two examples for models having discontinuities,

[http://eprints.esc.cam.ac.uk/2303/1/Deuss_JGR_2011JB008650.pdf](url)
[https://link.springer.com/article/10.1007/s12583-013-0363-9](url)

**Comment by crotwell** [comment]
Have added support for discontinuities in the core. The letter "y" is used for strictly upgoing compressional wave legs in the inner core, so I,y,J,j are allowed, along with Ied and Jed to interact with discontinuities in the core using `^, v, V`. For example, in a model with discontinuities at 3000 and 6000 km depth (one in inner, one in outer core):
```
taup time -deg 90 -ph PKIv6000ykp,PKI^6000IKP,PKv3000kp,PK^3000KP --mod ic_discon.nd

Model: ic_discon
Distance   Depth   Phase         Travel    Ray Param  Takeoff  Incident  Purist    Purist
  (deg)     (km)   Name          Time (s)  p (s/deg)   (deg)    (deg)   Distance   Name 
-----------------------------------------------------------------------------------------
   90.00     0.0   PKv3000kp      804.24     4.415     13.31    13.31    90.00   = PKv3000kp  
   90.00     0.0   PKIv6000ykp   1167.32     0.432      1.29     1.29    90.00   = PKIv6000ykp
   90.00     0.0   PKI^6000IKP   1260.44     0.382      1.14     1.14   270.00   = PKI^6000IKP
   90.00     0.0   PK^3000KP     1806.77     2.451      7.34     7.34   270.00   = PK^3000KP  
```

**Comment by 79seismo** [comment]
Thank you! 5.5 years in the making!
