### ISSUE TITLE
Support core phase names PKPab, PKPbc, PKPcd and PKPdf

### ISSUE THREAD

**Issue by seisman** [crotwell/TauP#5]
In core studies, PKIKP is often named as PKPdf, PKiKP is sometimes named as PKPcd.

In the distance of ~146 - 152 degree, there are two arrivals for PKP phase. These two PKP arrivals are always named as PKPab and PKPbc in core studies, which turns in the upper and lower outer core, respectively.

I think it's very useful if TauP can support these core phase names, especially PKPab and PKPbc.

Reference: http://www.isc.ac.uk/standards/phases/

**Comment by crotwell** [comment]
The path difference between ab and bc is hard for TauP to differentiate as it does not correspond to a boundary in the model, rather just a retrograde section of the same phase path. As such supporting those phase names adds complexity to the code without significant benefit, so we choose not to support them when TauP was created.
