### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by NimaDolatabadi** [crotwell/TauP#6]
when I use `gradle` or `gradle build.gradle` it faces an error listed below:

`nima@NimaDa:~/TauP-2.4.5$ gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/home/nima/TauP-2.4.5/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'TauP'.
> Could not find method mavenRepo() for arguments [{url=http://www.seis.sc.edu/software/maven2}] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
nima@NimaDa:~/TauP-2.4.5$`

what is the problem and how to fix it?

**Comment by crotwell** [comment]
I'll look into this, but do you really need to recompile TauP? There is a precompiled download on the site:
http://www.seis.sc.edu/TauP

**Comment by crotwell** [comment]
Should be fixed in latest commit.

./gradlew eB

will build the jar and create the run scripts into build/explode
