### ISSUE TITLE
Add time column in taup_path

### ISSUE THREAD

**Issue by kuangdai** [crotwell/TauP#7]
Hi, 

I would like to add the time column in the output of taup_path. The code is easy to modify and I have done that (by appending calcTime after radius) without any Java experience. However, I have been stuck with re-compiling the code on Mac OS (Sierra). 

The re-compiling issue is the same as here: 
https://github.com/crotwell/TauP/issues/6

Since this is a piece of cake for you, I am wondering if you could spend a few minutes to compile the code for me? The modified source code is attached. 

Thanks a lot,
Kuangdai

```javascript
protected void printDistRadius(Writer out, double calcDist, double radius, double calcTime) throws IOException {
        if (outputFormat.equals(JSON)) {
            throw new RuntimeException("JSON output for TauP_Path not yet supported.");
        } else if (outputFormat.equals(SVG)) {
            double radian = (calcDist-90)*Math.PI/180;
            double x = radius*Math.cos(radian);
            double y = radius*Math.sin(radian);
            out.write(outForms.formatDistance(x)
                      + "  "
                      + outForms.formatDistance(y)
                      + "  "
                      + outForms.formatTime(calcTime));
        } else {
            out.write(outForms.formatDistance(calcDist)
                      + "  "
                      + outForms.formatDepth(radius)
                      + "  "
                      + outForms.formatTime(calcTime));
        }
        if (!gmtScript && !outputFormat.equals(SVG)) {
            printLatLon(out, calcDist);
        }
    }

// as well as four calls to the above function, e.g., line 195 & 222:
printDistRadius(out, calcDist, radiusOfEarth - calcDepth, calcTime);
```

**Comment by crotwell** [comment]
I'll try to get to this in next few days, hopefully also #6

**Comment by crotwell** [comment]
Sorry for long delay...

YOu should be able to recomplie on your own with latest on github

./gradlew eB
will rebuild into build/explode

**Comment by crotwell** [comment]
new prerelease here:
http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.5.0-SNAPSHOT.tgz
might help with this, taup_path now has a --withtime option that will output a third column with the time for each path point.
